### PR TITLE
Update to 0.5.3

### PR DESCRIPTION
**Pull request by max06**

### CODE REVIEW

**Comment by max06** [comment]
@mattxwang Can you update netlify to use ruby 3.2.2? Not sure if that changes something...

**Review by mattxwang — APPROVED** [review]
Interesting - I looked up this issue, and it seems like [there might be some issues with Ruby and caching](https://answers.netlify.com/t/cant-deploy-with-ruby-3-1-2/55728/47) (that might be ... not persistent?). I've re-run the build after clearing the cache and it [now works](https://app.netlify.com/sites/just-the-docs-template/deploys/648ea7b72348aa052ece5f7d), even though the GitHub status report is not updated.

Going to merge this, thanks!

**Comment by mattxwang** [comment]
As for 

> Can you update netlify to use ruby 3.2.2?

IIRC there were some problems with Jekyll (and specifically, Liquid) on ruby 3.2. I haven't looked into it a while, but let me add this to my personal backlog; ideally, we keep everything in sync (including our CI on the main repo, etc.).

**Comment by max06** [comment]
Ack, we should keep it in sync.
My local tests were done using Ruby 3.2.2 showing no issues with building or running the pages. I thought updating ruby on netlify could rule out potential caching issues. Is there a way to contact netlify to ask them whats going on?

**Comment by max06** [comment]
Ha, missed your first comment...

I just checked why my ruby 3.2.2 works: I accidentally solved the issue 2 weeks ago in https://github.com/just-the-docs/just-the-docs-template/commit/9f745ce63bcb94d0450599e15ec1cb3483f80804 by regenerating the whole lockfile. My current tests show the gem-based use is compatible with ruby 3.1 and 3.2, as well as jekyll 3.9.3 and 4.3.2. I'm gonna test the other installation methods as well.

**Pull request merged**
