### PR TITLE
fix: :arrow_up: Update to jekyll 4.3.2 and jtd 0.5.1

### PR DESCRIPTION
**Pull request by max06**
The template turned out to be not builable with the versions set in the lockfile.

---

I noticed jekyll is not strictly pinned. Not sure what way to go, updating the version contraint or the lockfile...

### CODE REVIEW

**Comment by max06** [comment]
Lacking access ... @mattxwang, please take over ;)

**Review by mattxwang — APPROVED** [review]
Thanks for the catch!

**Review by mattxwang — CHANGES_REQUESTED** [review]
Actually, going to lightly retract that - I had originally thought that the issue was with Netlify, but it seems like after some tinkering the updated versions for the gems are wrong; are you able to take a look at this?

**Comment by mattxwang** [comment]
I also just merged an update replicating the Netlify build on CI, which should give you more insight on what's happening.

**Comment by max06** [comment]
Looks like netlify uses Ruby 2.7, which seems to be incompatible with the sass-plugin.

**Comment by mattxwang** [comment]
> Looks like netlify uses Ruby 2.7, which seems to be incompatible with the sass-plugin.

Hm, I might be wrong, but I explicitly loaded Ruby 3.1.2 into the Netlify builder; for example, in the latest [deploy log](https://app.netlify.com/sites/just-the-docs-template/deploys/647e2920e33b7d0008c94de1):

> 11:27:47 AM: build-image version: ffab3dbd3296c17f3cd4edff692372d98e6d8a8f (focal)
> 11:27:47 AM: buildbot version: f6128af83ac177740bc729eee55d8c066e4a11a4
> 11:27:47 AM: Fetching cached dependencies
> 11:27:47 AM: Starting to download cache of 143.5MB
> 11:27:49 AM: Finished downloading cache in 2.212s
> 11:27:49 AM: Starting to extract cache
> 11:27:50 AM: Finished extracting cache in 831ms
> 11:27:50 AM: Finished fetching cache in 3.092s
> 11:27:50 AM: Starting to prepare the repo for build
> 11:27:50 AM: Preparing Git Reference pull/22/head
> 11:27:52 AM: Starting to install dependencies
> 11:27:52 AM: Python version set to 3.8
> 11:27:52 AM: Attempting Ruby version 3.1.2, read from environment
> 11:27:52 AM: Started restoring cached Ruby version
> 11:27:52 AM: Finished restoring cached Ruby version
> 11:27:53 AM: Using Ruby version 3.1.2
> 11:27:53 AM: Using Bundler version 2.3.9 from Gemfile.lock
> 11:27:53 AM: Started restoring cached ruby gems
> 11:27:53 AM: Finished restoring cached ruby gems
> 11:27:53 AM: Installing gem bundle
> 11:27:53 AM: [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '/opt/build/cache/bundle'`, and stop using this flag
> 11:27:53 AM: [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
> 11:27:54 AM: Fetching gem metadata from https://rubygems.org/...........
> 11:27:54 AM: Your bundle is locked to sass-embedded (1.62.1-x86_64-linux) from rubygems
> 11:27:54 AM: repository https://rubygems.org/ or installed locally, but that version can no
> 11:27:54 AM: longer be found in that source. That means the author of sass-embedded
> 11:27:54 AM: (1.62.1-x86_64-linux) has removed it. You'll need to update your bundle to a
> version other than sass-embedded (1.62.1-x86_64-linux) that hasn't been removed
> in order to install.
> 11:27:54 AM: Error during gem install
> 11:27:55 AM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
> 11:27:54 AM: Build was terminated: dependency_installation script returned non-zero exit code: 1
> 11:27:54 AM: Failing build: Failed to install dependencies

Taking a look at the [versions of `sass-embedded`](https://rubygems.org/gems/sass-embedded/versions), there doesn't seem to be a version directly for `x86_64-linux`. Perhaps either unplatforming it and/or picking the right platform should resolve the build error?

**Comment by max06** [comment]
I generated a new lockfile for testing ... and it broke even more. 😂

**Review by mattxwang — APPROVED** [review]
I think there's something wrong with the Netlify <-> Actions integration; I have manually redeployed the branch and it works. With that in mind, I'll merge this in; thanks for the contribution @max06!

**Pull request merged**
